# fly.toml app configuration file generated for quantscrape on 2024-01-06T14:30:27+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quantscrape"
primary_region = "lhr"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
